projects:
  awshackathonapi:
    schemaPath: aws-client/graphql/schema.json
    includes:
      - aws-client/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: aws-client/graphql
extensions:
  amplify:
    version: 3
